/**
 * Generated by orval v6.16.0 🍺
 * Do not edit manually.
 * Tspec API
 * OpenAPI spec version: 0.0.1
 */

export interface CreateDiaryDto {
  title: string;
  content: string;
  weather?: string;
  mood?: string;
  tags?: string[];
}
