/**
 * Generated by orval v6.16.0 🍺
 * Do not edit manually.
 * Tspec API
 * OpenAPI spec version: 0.0.1
 */
import type {DiaryApiSpecGetDiarySummary200Data} from './diaryApiSpecGetDiarySummary200Data';

export type DiaryApiSpecGetDiarySummary200 = {
  message: string;
  data: DiaryApiSpecGetDiarySummary200Data;
};
