/**
 * Generated by orval v6.16.0 🍺
 * Do not edit manually.
 * Tspec API
 * OpenAPI spec version: 0.0.1
 */

export type DiaryApiSpecGetDiaryId200Data = {
  id: number;
  title: string;
  content: string;
  createdAt: string;
  weather: string;
  mood: string;
  userId: number;
};
