/**
 * Generated by orval v6.16.0 🍺
 * Do not edit manually.
 * Tspec API
 * OpenAPI spec version: 0.0.1
 */
import type {DiaryApiSpecGetDiaryId200Data} from './diaryApiSpecGetDiaryId200Data';

export type DiaryApiSpecGetDiaryId200 = {
  message: string;
  data: DiaryApiSpecGetDiaryId200Data;
};
