/**
 * Generated by orval v6.16.0 🍺
 * Do not edit manually.
 * Tspec API
 * OpenAPI spec version: 0.0.1
 */
import type {DiaryApiSpecGetDiary200DataItemsItem} from './diaryApiSpecGetDiary200DataItemsItem';

export type DiaryApiSpecGetDiary200Data = {
  page: number;
  size: number;
  totalCount: number;
  totalPage: number;
  hasNextPage: boolean;
  hasPreviousPage: boolean;
  items: DiaryApiSpecGetDiary200DataItemsItem[];
};
