/**
 * Generated by orval v6.16.0 🍺
 * Do not edit manually.
 * Tspec API
 * OpenAPI spec version: 0.0.1
 */

export type UsersApiSpecPostUsersSignupBody = {
  email: string;
  nickname: string;
  password: string;
};
