/**
 * Generated by orval v6.16.0 🍺
 * Do not edit manually.
 * Tspec API
 * OpenAPI spec version: 0.0.1
 */
import type {DiaryApiSpecGetDiary200Data} from './diaryApiSpecGetDiary200Data';

export type DiaryApiSpecGetDiary200 = {
  message: string;
  data: DiaryApiSpecGetDiary200Data;
};
