/**
 * Generated by orval v6.16.0 🍺
 * Do not edit manually.
 * Tspec API
 * OpenAPI spec version: 0.0.1
 */

export type DiaryApiSpecGetDiaryParams = {
  size: number;
  page: number;
  content: string;
  year: string;
  month: string;
};
